# Generated by Django 5.2.17 on 2026-09-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_access_token',
            field=models.TextField(blank=True, default='', verbose_name='access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='access checked'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='refresh token'),
        ),
    ]
